#-
# Copyright (c) 2020-2021 Jessica Clarke
#
# @BERI_LICENSE_HEADER_START@
#
# Licensed to BERI Open Systems C.I.C. (BERI) under one or more contributor
# license agreements.  See the NOTICE file distributed with this work for
# additional information regarding copyright ownership.  BERI licenses this
# file to you under the BERI Hardware-Software License, Version 1.0 (the
# "License"); you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at:
#
#   http://www.beri-open-systems.org/legal/license-1-0.txt
#
# Unless required by applicable law or agreed to in writing, Work distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations under the License.
#
# @BERI_LICENSE_HEADER_END@
#

# DRC waivers

set ddr_tie_off_ibufs [get_cells -quiet -hier -filter {IS_PRIMITIVE && REF_NAME == IBUFCTRL} -regexp {ddrs/DDR./tie_off_.*}]
create_waiver -quiet -type DRC -id {BUFC-1} -user jrtc27 -description "Tied-off DDR IOBUFs" -objects $ddr_tie_off_ibufs

# NB: Also results in RTSTAT-10 warnings due to the use of XSDB_SLV_DIS but
# those unfortunately cannot be waived.

# Physical constraints

set_property DRIVE 8 [get_ports {ddr4_sdram_c?_reset_n}]

set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_sdram_c?_act_n}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_sdram_c?_adr[*]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_sdram_c?_ba[*]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_sdram_c?_bg}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {ddr4_sdram_c?_ck_?}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_sdram_c?_cke}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_sdram_c?_cs_n}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_sdram_c?_dm_dbi_n[*]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_sdram_c?_dq[*]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_sdram_c?_dqs_?[*]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_sdram_c?_odt}]
set_property IOSTANDARD LVCMOS12 [get_ports {ddr4_sdram_c?_reset_n}]
set_property IOSTANDARD DIFF_SSTL12 [get_ports {ddr4_sdram_c?_sys_clk_?}]

set_property ODT RTT_40 [get_ports {ddr4_sdram_c?_dm_dbi_n[*]}]
set_property ODT RTT_40 [get_ports {ddr4_sdram_c?_dq[*]}]
set_property ODT RTT_40 [get_ports {ddr4_sdram_c?_dqs_?[*]}]
set_property ODT RTT_40 [get_ports {ddr4_sdram_c?_dm_dbi_n[*]}]
set_property ODT RTT_40 [get_ports {ddr4_sdram_c?_dq[*]}]
set_property ODT RTT_40 [get_ports {ddr4_sdram_c?_dqs_?[*]}]
set_property ODT RTT_NONE [get_ports {ddr4_sdram_c?_sys_clk_?}]

set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_sdram_c?_act_n}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_sdram_c?_adr[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_sdram_c?_ba[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_sdram_c?_bg}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_sdram_c?_ck_?}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_sdram_c?_cke}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_sdram_c?_dm_dbi_n[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_sdram_c?_dq[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_sdram_c?_dqs_?[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_sdram_c?_odt}]

set_property SLEW FAST [get_ports {ddr4_sdram_c?_act_n}]
set_property SLEW FAST [get_ports {ddr4_sdram_c?_adr[*]}]
set_property SLEW FAST [get_ports {ddr4_sdram_c?_ba[*]}]
set_property SLEW FAST [get_ports {ddr4_sdram_c?_bg}]
set_property SLEW FAST [get_ports {ddr4_sdram_c?_ck_?}]
set_property SLEW FAST [get_ports {ddr4_sdram_c?_cke}]
set_property SLEW FAST [get_ports {ddr4_sdram_c?_cs_n}]
set_property SLEW FAST [get_ports {ddr4_sdram_c?_dm_dbi_n[*]}]
set_property SLEW FAST [get_ports {ddr4_sdram_c?_dq[*]}]
set_property SLEW FAST [get_ports {ddr4_sdram_c?_dqs_?[*]}]
set_property SLEW FAST [get_ports {ddr4_sdram_c?_odt}]

set_property BOARD_PIN c1_ddr4_act_n [get_ports {ddr4_sdram_c1_act_n}]
set_property BOARD_PIN c1_ddr4_adr0 [get_ports {ddr4_sdram_c1_adr[0]}]
set_property BOARD_PIN c1_ddr4_adr1 [get_ports {ddr4_sdram_c1_adr[1]}]
set_property BOARD_PIN c1_ddr4_adr2 [get_ports {ddr4_sdram_c1_adr[2]}]
set_property BOARD_PIN c1_ddr4_adr3 [get_ports {ddr4_sdram_c1_adr[3]}]
set_property BOARD_PIN c1_ddr4_adr4 [get_ports {ddr4_sdram_c1_adr[4]}]
set_property BOARD_PIN c1_ddr4_adr5 [get_ports {ddr4_sdram_c1_adr[5]}]
set_property BOARD_PIN c1_ddr4_adr6 [get_ports {ddr4_sdram_c1_adr[6]}]
set_property BOARD_PIN c1_ddr4_adr7 [get_ports {ddr4_sdram_c1_adr[7]}]
set_property BOARD_PIN c1_ddr4_adr8 [get_ports {ddr4_sdram_c1_adr[8]}]
set_property BOARD_PIN c1_ddr4_adr9 [get_ports {ddr4_sdram_c1_adr[9]}]
set_property BOARD_PIN c1_ddr4_adr10 [get_ports {ddr4_sdram_c1_adr[10]}]
set_property BOARD_PIN c1_ddr4_adr11 [get_ports {ddr4_sdram_c1_adr[11]}]
set_property BOARD_PIN c1_ddr4_adr12 [get_ports {ddr4_sdram_c1_adr[12]}]
set_property BOARD_PIN c1_ddr4_adr13 [get_ports {ddr4_sdram_c1_adr[13]}]
set_property BOARD_PIN c1_ddr4_adr14 [get_ports {ddr4_sdram_c1_adr[14]}]
set_property BOARD_PIN c1_ddr4_adr15 [get_ports {ddr4_sdram_c1_adr[15]}]
set_property BOARD_PIN c1_ddr4_adr16 [get_ports {ddr4_sdram_c1_adr[16]}]
set_property BOARD_PIN c1_ddr4_ba0 [get_ports {ddr4_sdram_c1_ba[0]}]
set_property BOARD_PIN c1_ddr4_ba1 [get_ports {ddr4_sdram_c1_ba[1]}]
set_property BOARD_PIN c1_ddr4_bg [get_ports {ddr4_sdram_c1_bg}]
set_property BOARD_PIN c1_ddr4_cke [get_ports {ddr4_sdram_c1_cke}]
set_property BOARD_PIN c1_ddr4_ck_c [get_ports {ddr4_sdram_c1_ck_n}]
set_property BOARD_PIN c1_ddr4_ck_t [get_ports {ddr4_sdram_c1_ck_p}]
set_property BOARD_PIN c1_ddr4_cs_n [get_ports {ddr4_sdram_c1_cs_n}]
set_property BOARD_PIN c1_ddr4_dm_dbi_n0 [get_ports {ddr4_sdram_c1_dm_dbi_n[0]}]
set_property BOARD_PIN c1_ddr4_dm_dbi_n1 [get_ports {ddr4_sdram_c1_dm_dbi_n[1]}]
set_property BOARD_PIN c1_ddr4_dm_dbi_n2 [get_ports {ddr4_sdram_c1_dm_dbi_n[2]}]
set_property BOARD_PIN c1_ddr4_dm_dbi_n3 [get_ports {ddr4_sdram_c1_dm_dbi_n[3]}]
set_property BOARD_PIN c1_ddr4_dm_dbi_n4 [get_ports {ddr4_sdram_c1_dm_dbi_n[4]}]
set_property BOARD_PIN c1_ddr4_dm_dbi_n5 [get_ports {ddr4_sdram_c1_dm_dbi_n[5]}]
set_property BOARD_PIN c1_ddr4_dm_dbi_n6 [get_ports {ddr4_sdram_c1_dm_dbi_n[6]}]
set_property BOARD_PIN c1_ddr4_dm_dbi_n7 [get_ports {ddr4_sdram_c1_dm_dbi_n[7]}]
set_property BOARD_PIN c1_ddr4_dqs_c0 [get_ports {ddr4_sdram_c1_dqs_n[0]}]
set_property BOARD_PIN c1_ddr4_dqs_c1 [get_ports {ddr4_sdram_c1_dqs_n[1]}]
set_property BOARD_PIN c1_ddr4_dqs_c2 [get_ports {ddr4_sdram_c1_dqs_n[2]}]
set_property BOARD_PIN c1_ddr4_dqs_c3 [get_ports {ddr4_sdram_c1_dqs_n[3]}]
set_property BOARD_PIN c1_ddr4_dqs_c4 [get_ports {ddr4_sdram_c1_dqs_n[4]}]
set_property BOARD_PIN c1_ddr4_dqs_c5 [get_ports {ddr4_sdram_c1_dqs_n[5]}]
set_property BOARD_PIN c1_ddr4_dqs_c6 [get_ports {ddr4_sdram_c1_dqs_n[6]}]
set_property BOARD_PIN c1_ddr4_dqs_c7 [get_ports {ddr4_sdram_c1_dqs_n[7]}]
set_property BOARD_PIN c1_ddr4_dqs_t0 [get_ports {ddr4_sdram_c1_dqs_p[0]}]
set_property BOARD_PIN c1_ddr4_dqs_t1 [get_ports {ddr4_sdram_c1_dqs_p[1]}]
set_property BOARD_PIN c1_ddr4_dqs_t2 [get_ports {ddr4_sdram_c1_dqs_p[2]}]
set_property BOARD_PIN c1_ddr4_dqs_t3 [get_ports {ddr4_sdram_c1_dqs_p[3]}]
set_property BOARD_PIN c1_ddr4_dqs_t4 [get_ports {ddr4_sdram_c1_dqs_p[4]}]
set_property BOARD_PIN c1_ddr4_dqs_t5 [get_ports {ddr4_sdram_c1_dqs_p[5]}]
set_property BOARD_PIN c1_ddr4_dqs_t6 [get_ports {ddr4_sdram_c1_dqs_p[6]}]
set_property BOARD_PIN c1_ddr4_dqs_t7 [get_ports {ddr4_sdram_c1_dqs_p[7]}]
set_property BOARD_PIN c1_ddr4_dq0 [get_ports {ddr4_sdram_c1_dq[0]}]
set_property BOARD_PIN c1_ddr4_dq1 [get_ports {ddr4_sdram_c1_dq[1]}]
set_property BOARD_PIN c1_ddr4_dq2 [get_ports {ddr4_sdram_c1_dq[2]}]
set_property BOARD_PIN c1_ddr4_dq3 [get_ports {ddr4_sdram_c1_dq[3]}]
set_property BOARD_PIN c1_ddr4_dq4 [get_ports {ddr4_sdram_c1_dq[4]}]
set_property BOARD_PIN c1_ddr4_dq5 [get_ports {ddr4_sdram_c1_dq[5]}]
set_property BOARD_PIN c1_ddr4_dq6 [get_ports {ddr4_sdram_c1_dq[6]}]
set_property BOARD_PIN c1_ddr4_dq7 [get_ports {ddr4_sdram_c1_dq[7]}]
set_property BOARD_PIN c1_ddr4_dq8 [get_ports {ddr4_sdram_c1_dq[8]}]
set_property BOARD_PIN c1_ddr4_dq9 [get_ports {ddr4_sdram_c1_dq[9]}]
set_property BOARD_PIN c1_ddr4_dq10 [get_ports {ddr4_sdram_c1_dq[10]}]
set_property BOARD_PIN c1_ddr4_dq11 [get_ports {ddr4_sdram_c1_dq[11]}]
set_property BOARD_PIN c1_ddr4_dq12 [get_ports {ddr4_sdram_c1_dq[12]}]
set_property BOARD_PIN c1_ddr4_dq13 [get_ports {ddr4_sdram_c1_dq[13]}]
set_property BOARD_PIN c1_ddr4_dq14 [get_ports {ddr4_sdram_c1_dq[14]}]
set_property BOARD_PIN c1_ddr4_dq15 [get_ports {ddr4_sdram_c1_dq[15]}]
set_property BOARD_PIN c1_ddr4_dq16 [get_ports {ddr4_sdram_c1_dq[16]}]
set_property BOARD_PIN c1_ddr4_dq17 [get_ports {ddr4_sdram_c1_dq[17]}]
set_property BOARD_PIN c1_ddr4_dq18 [get_ports {ddr4_sdram_c1_dq[18]}]
set_property BOARD_PIN c1_ddr4_dq19 [get_ports {ddr4_sdram_c1_dq[19]}]
set_property BOARD_PIN c1_ddr4_dq20 [get_ports {ddr4_sdram_c1_dq[20]}]
set_property BOARD_PIN c1_ddr4_dq21 [get_ports {ddr4_sdram_c1_dq[21]}]
set_property BOARD_PIN c1_ddr4_dq22 [get_ports {ddr4_sdram_c1_dq[22]}]
set_property BOARD_PIN c1_ddr4_dq23 [get_ports {ddr4_sdram_c1_dq[23]}]
set_property BOARD_PIN c1_ddr4_dq24 [get_ports {ddr4_sdram_c1_dq[24]}]
set_property BOARD_PIN c1_ddr4_dq25 [get_ports {ddr4_sdram_c1_dq[25]}]
set_property BOARD_PIN c1_ddr4_dq26 [get_ports {ddr4_sdram_c1_dq[26]}]
set_property BOARD_PIN c1_ddr4_dq27 [get_ports {ddr4_sdram_c1_dq[27]}]
set_property BOARD_PIN c1_ddr4_dq28 [get_ports {ddr4_sdram_c1_dq[28]}]
set_property BOARD_PIN c1_ddr4_dq29 [get_ports {ddr4_sdram_c1_dq[29]}]
set_property BOARD_PIN c1_ddr4_dq30 [get_ports {ddr4_sdram_c1_dq[30]}]
set_property BOARD_PIN c1_ddr4_dq31 [get_ports {ddr4_sdram_c1_dq[31]}]
set_property BOARD_PIN c1_ddr4_dq32 [get_ports {ddr4_sdram_c1_dq[32]}]
set_property BOARD_PIN c1_ddr4_dq33 [get_ports {ddr4_sdram_c1_dq[33]}]
set_property BOARD_PIN c1_ddr4_dq34 [get_ports {ddr4_sdram_c1_dq[34]}]
set_property BOARD_PIN c1_ddr4_dq35 [get_ports {ddr4_sdram_c1_dq[35]}]
set_property BOARD_PIN c1_ddr4_dq36 [get_ports {ddr4_sdram_c1_dq[36]}]
set_property BOARD_PIN c1_ddr4_dq37 [get_ports {ddr4_sdram_c1_dq[37]}]
set_property BOARD_PIN c1_ddr4_dq38 [get_ports {ddr4_sdram_c1_dq[38]}]
set_property BOARD_PIN c1_ddr4_dq39 [get_ports {ddr4_sdram_c1_dq[39]}]
set_property BOARD_PIN c1_ddr4_dq40 [get_ports {ddr4_sdram_c1_dq[40]}]
set_property BOARD_PIN c1_ddr4_dq41 [get_ports {ddr4_sdram_c1_dq[41]}]
set_property BOARD_PIN c1_ddr4_dq42 [get_ports {ddr4_sdram_c1_dq[42]}]
set_property BOARD_PIN c1_ddr4_dq43 [get_ports {ddr4_sdram_c1_dq[43]}]
set_property BOARD_PIN c1_ddr4_dq44 [get_ports {ddr4_sdram_c1_dq[44]}]
set_property BOARD_PIN c1_ddr4_dq45 [get_ports {ddr4_sdram_c1_dq[45]}]
set_property BOARD_PIN c1_ddr4_dq46 [get_ports {ddr4_sdram_c1_dq[46]}]
set_property BOARD_PIN c1_ddr4_dq47 [get_ports {ddr4_sdram_c1_dq[47]}]
set_property BOARD_PIN c1_ddr4_dq48 [get_ports {ddr4_sdram_c1_dq[48]}]
set_property BOARD_PIN c1_ddr4_dq49 [get_ports {ddr4_sdram_c1_dq[49]}]
set_property BOARD_PIN c1_ddr4_dq50 [get_ports {ddr4_sdram_c1_dq[50]}]
set_property BOARD_PIN c1_ddr4_dq51 [get_ports {ddr4_sdram_c1_dq[51]}]
set_property BOARD_PIN c1_ddr4_dq52 [get_ports {ddr4_sdram_c1_dq[52]}]
set_property BOARD_PIN c1_ddr4_dq53 [get_ports {ddr4_sdram_c1_dq[53]}]
set_property BOARD_PIN c1_ddr4_dq54 [get_ports {ddr4_sdram_c1_dq[54]}]
set_property BOARD_PIN c1_ddr4_dq55 [get_ports {ddr4_sdram_c1_dq[55]}]
set_property BOARD_PIN c1_ddr4_dq56 [get_ports {ddr4_sdram_c1_dq[56]}]
set_property BOARD_PIN c1_ddr4_dq57 [get_ports {ddr4_sdram_c1_dq[57]}]
set_property BOARD_PIN c1_ddr4_dq58 [get_ports {ddr4_sdram_c1_dq[58]}]
set_property BOARD_PIN c1_ddr4_dq59 [get_ports {ddr4_sdram_c1_dq[59]}]
set_property BOARD_PIN c1_ddr4_dq60 [get_ports {ddr4_sdram_c1_dq[60]}]
set_property BOARD_PIN c1_ddr4_dq61 [get_ports {ddr4_sdram_c1_dq[61]}]
set_property BOARD_PIN c1_ddr4_dq62 [get_ports {ddr4_sdram_c1_dq[62]}]
set_property BOARD_PIN c1_ddr4_dq63 [get_ports {ddr4_sdram_c1_dq[63]}]
set_property BOARD_PIN c1_ddr4_odt [get_ports {ddr4_sdram_c1_odt}]
set_property BOARD_PIN c1_ddr4_reset_n [get_ports {ddr4_sdram_c1_reset_n}]
set_property BOARD_PIN default_250mhz_clk1_n [get_ports {ddr4_sdram_c1_sys_clk_n}]
set_property BOARD_PIN default_250mhz_clk1_p [get_ports {ddr4_sdram_c1_sys_clk_p}]
set_property BOARD_PIN c2_ddr4_act_n [get_ports {ddr4_sdram_c2_act_n}]
set_property BOARD_PIN c2_ddr4_adr0 [get_ports {ddr4_sdram_c2_adr[0]}]
set_property BOARD_PIN c2_ddr4_adr1 [get_ports {ddr4_sdram_c2_adr[1]}]
set_property BOARD_PIN c2_ddr4_adr2 [get_ports {ddr4_sdram_c2_adr[2]}]
set_property BOARD_PIN c2_ddr4_adr3 [get_ports {ddr4_sdram_c2_adr[3]}]
set_property BOARD_PIN c2_ddr4_adr4 [get_ports {ddr4_sdram_c2_adr[4]}]
set_property BOARD_PIN c2_ddr4_adr5 [get_ports {ddr4_sdram_c2_adr[5]}]
set_property BOARD_PIN c2_ddr4_adr6 [get_ports {ddr4_sdram_c2_adr[6]}]
set_property BOARD_PIN c2_ddr4_adr7 [get_ports {ddr4_sdram_c2_adr[7]}]
set_property BOARD_PIN c2_ddr4_adr8 [get_ports {ddr4_sdram_c2_adr[8]}]
set_property BOARD_PIN c2_ddr4_adr9 [get_ports {ddr4_sdram_c2_adr[9]}]
set_property BOARD_PIN c2_ddr4_adr10 [get_ports {ddr4_sdram_c2_adr[10]}]
set_property BOARD_PIN c2_ddr4_adr11 [get_ports {ddr4_sdram_c2_adr[11]}]
set_property BOARD_PIN c2_ddr4_adr12 [get_ports {ddr4_sdram_c2_adr[12]}]
set_property BOARD_PIN c2_ddr4_adr13 [get_ports {ddr4_sdram_c2_adr[13]}]
set_property BOARD_PIN c2_ddr4_adr14 [get_ports {ddr4_sdram_c2_adr[14]}]
set_property BOARD_PIN c2_ddr4_adr15 [get_ports {ddr4_sdram_c2_adr[15]}]
set_property BOARD_PIN c2_ddr4_adr16 [get_ports {ddr4_sdram_c2_adr[16]}]
set_property BOARD_PIN c2_ddr4_ba0 [get_ports {ddr4_sdram_c2_ba[0]}]
set_property BOARD_PIN c2_ddr4_ba1 [get_ports {ddr4_sdram_c2_ba[1]}]
set_property BOARD_PIN c2_ddr4_bg [get_ports {ddr4_sdram_c2_bg}]
set_property BOARD_PIN c2_ddr4_cke [get_ports {ddr4_sdram_c2_cke}]
set_property BOARD_PIN c2_ddr4_ck_c [get_ports {ddr4_sdram_c2_ck_n}]
set_property BOARD_PIN c2_ddr4_ck_t [get_ports {ddr4_sdram_c2_ck_p}]
set_property BOARD_PIN c2_ddr4_cs_n [get_ports {ddr4_sdram_c2_cs_n}]
set_property BOARD_PIN c2_ddr4_dm_dbi_n0 [get_ports {ddr4_sdram_c2_dm_dbi_n[0]}]
set_property BOARD_PIN c2_ddr4_dm_dbi_n1 [get_ports {ddr4_sdram_c2_dm_dbi_n[1]}]
set_property BOARD_PIN c2_ddr4_dm_dbi_n2 [get_ports {ddr4_sdram_c2_dm_dbi_n[2]}]
set_property BOARD_PIN c2_ddr4_dm_dbi_n3 [get_ports {ddr4_sdram_c2_dm_dbi_n[3]}]
set_property BOARD_PIN c2_ddr4_dm_dbi_n4 [get_ports {ddr4_sdram_c2_dm_dbi_n[4]}]
set_property BOARD_PIN c2_ddr4_dm_dbi_n5 [get_ports {ddr4_sdram_c2_dm_dbi_n[5]}]
set_property BOARD_PIN c2_ddr4_dm_dbi_n6 [get_ports {ddr4_sdram_c2_dm_dbi_n[6]}]
set_property BOARD_PIN c2_ddr4_dm_dbi_n7 [get_ports {ddr4_sdram_c2_dm_dbi_n[7]}]
set_property BOARD_PIN c2_ddr4_dqs_c0 [get_ports {ddr4_sdram_c2_dqs_n[0]}]
set_property BOARD_PIN c2_ddr4_dqs_c1 [get_ports {ddr4_sdram_c2_dqs_n[1]}]
set_property BOARD_PIN c2_ddr4_dqs_c2 [get_ports {ddr4_sdram_c2_dqs_n[2]}]
set_property BOARD_PIN c2_ddr4_dqs_c3 [get_ports {ddr4_sdram_c2_dqs_n[3]}]
set_property BOARD_PIN c2_ddr4_dqs_c4 [get_ports {ddr4_sdram_c2_dqs_n[4]}]
set_property BOARD_PIN c2_ddr4_dqs_c5 [get_ports {ddr4_sdram_c2_dqs_n[5]}]
set_property BOARD_PIN c2_ddr4_dqs_c6 [get_ports {ddr4_sdram_c2_dqs_n[6]}]
set_property BOARD_PIN c2_ddr4_dqs_c7 [get_ports {ddr4_sdram_c2_dqs_n[7]}]
set_property BOARD_PIN c2_ddr4_dqs_t0 [get_ports {ddr4_sdram_c2_dqs_p[0]}]
set_property BOARD_PIN c2_ddr4_dqs_t1 [get_ports {ddr4_sdram_c2_dqs_p[1]}]
set_property BOARD_PIN c2_ddr4_dqs_t2 [get_ports {ddr4_sdram_c2_dqs_p[2]}]
set_property BOARD_PIN c2_ddr4_dqs_t3 [get_ports {ddr4_sdram_c2_dqs_p[3]}]
set_property BOARD_PIN c2_ddr4_dqs_t4 [get_ports {ddr4_sdram_c2_dqs_p[4]}]
set_property BOARD_PIN c2_ddr4_dqs_t5 [get_ports {ddr4_sdram_c2_dqs_p[5]}]
set_property BOARD_PIN c2_ddr4_dqs_t6 [get_ports {ddr4_sdram_c2_dqs_p[6]}]
set_property BOARD_PIN c2_ddr4_dqs_t7 [get_ports {ddr4_sdram_c2_dqs_p[7]}]
set_property BOARD_PIN c2_ddr4_dq0 [get_ports {ddr4_sdram_c2_dq[0]}]
set_property BOARD_PIN c2_ddr4_dq1 [get_ports {ddr4_sdram_c2_dq[1]}]
set_property BOARD_PIN c2_ddr4_dq2 [get_ports {ddr4_sdram_c2_dq[2]}]
set_property BOARD_PIN c2_ddr4_dq3 [get_ports {ddr4_sdram_c2_dq[3]}]
set_property BOARD_PIN c2_ddr4_dq4 [get_ports {ddr4_sdram_c2_dq[4]}]
set_property BOARD_PIN c2_ddr4_dq5 [get_ports {ddr4_sdram_c2_dq[5]}]
set_property BOARD_PIN c2_ddr4_dq6 [get_ports {ddr4_sdram_c2_dq[6]}]
set_property BOARD_PIN c2_ddr4_dq7 [get_ports {ddr4_sdram_c2_dq[7]}]
set_property BOARD_PIN c2_ddr4_dq8 [get_ports {ddr4_sdram_c2_dq[8]}]
set_property BOARD_PIN c2_ddr4_dq9 [get_ports {ddr4_sdram_c2_dq[9]}]
set_property BOARD_PIN c2_ddr4_dq10 [get_ports {ddr4_sdram_c2_dq[10]}]
set_property BOARD_PIN c2_ddr4_dq11 [get_ports {ddr4_sdram_c2_dq[11]}]
set_property BOARD_PIN c2_ddr4_dq12 [get_ports {ddr4_sdram_c2_dq[12]}]
set_property BOARD_PIN c2_ddr4_dq13 [get_ports {ddr4_sdram_c2_dq[13]}]
set_property BOARD_PIN c2_ddr4_dq14 [get_ports {ddr4_sdram_c2_dq[14]}]
set_property BOARD_PIN c2_ddr4_dq15 [get_ports {ddr4_sdram_c2_dq[15]}]
set_property BOARD_PIN c2_ddr4_dq16 [get_ports {ddr4_sdram_c2_dq[16]}]
set_property BOARD_PIN c2_ddr4_dq17 [get_ports {ddr4_sdram_c2_dq[17]}]
set_property BOARD_PIN c2_ddr4_dq18 [get_ports {ddr4_sdram_c2_dq[18]}]
set_property BOARD_PIN c2_ddr4_dq19 [get_ports {ddr4_sdram_c2_dq[19]}]
set_property BOARD_PIN c2_ddr4_dq20 [get_ports {ddr4_sdram_c2_dq[20]}]
set_property BOARD_PIN c2_ddr4_dq21 [get_ports {ddr4_sdram_c2_dq[21]}]
set_property BOARD_PIN c2_ddr4_dq22 [get_ports {ddr4_sdram_c2_dq[22]}]
set_property BOARD_PIN c2_ddr4_dq23 [get_ports {ddr4_sdram_c2_dq[23]}]
set_property BOARD_PIN c2_ddr4_dq24 [get_ports {ddr4_sdram_c2_dq[24]}]
set_property BOARD_PIN c2_ddr4_dq25 [get_ports {ddr4_sdram_c2_dq[25]}]
set_property BOARD_PIN c2_ddr4_dq26 [get_ports {ddr4_sdram_c2_dq[26]}]
set_property BOARD_PIN c2_ddr4_dq27 [get_ports {ddr4_sdram_c2_dq[27]}]
set_property BOARD_PIN c2_ddr4_dq28 [get_ports {ddr4_sdram_c2_dq[28]}]
set_property BOARD_PIN c2_ddr4_dq29 [get_ports {ddr4_sdram_c2_dq[29]}]
set_property BOARD_PIN c2_ddr4_dq30 [get_ports {ddr4_sdram_c2_dq[30]}]
set_property BOARD_PIN c2_ddr4_dq31 [get_ports {ddr4_sdram_c2_dq[31]}]
set_property BOARD_PIN c2_ddr4_dq32 [get_ports {ddr4_sdram_c2_dq[32]}]
set_property BOARD_PIN c2_ddr4_dq33 [get_ports {ddr4_sdram_c2_dq[33]}]
set_property BOARD_PIN c2_ddr4_dq34 [get_ports {ddr4_sdram_c2_dq[34]}]
set_property BOARD_PIN c2_ddr4_dq35 [get_ports {ddr4_sdram_c2_dq[35]}]
set_property BOARD_PIN c2_ddr4_dq36 [get_ports {ddr4_sdram_c2_dq[36]}]
set_property BOARD_PIN c2_ddr4_dq37 [get_ports {ddr4_sdram_c2_dq[37]}]
set_property BOARD_PIN c2_ddr4_dq38 [get_ports {ddr4_sdram_c2_dq[38]}]
set_property BOARD_PIN c2_ddr4_dq39 [get_ports {ddr4_sdram_c2_dq[39]}]
set_property BOARD_PIN c2_ddr4_dq40 [get_ports {ddr4_sdram_c2_dq[40]}]
set_property BOARD_PIN c2_ddr4_dq41 [get_ports {ddr4_sdram_c2_dq[41]}]
set_property BOARD_PIN c2_ddr4_dq42 [get_ports {ddr4_sdram_c2_dq[42]}]
set_property BOARD_PIN c2_ddr4_dq43 [get_ports {ddr4_sdram_c2_dq[43]}]
set_property BOARD_PIN c2_ddr4_dq44 [get_ports {ddr4_sdram_c2_dq[44]}]
set_property BOARD_PIN c2_ddr4_dq45 [get_ports {ddr4_sdram_c2_dq[45]}]
set_property BOARD_PIN c2_ddr4_dq46 [get_ports {ddr4_sdram_c2_dq[46]}]
set_property BOARD_PIN c2_ddr4_dq47 [get_ports {ddr4_sdram_c2_dq[47]}]
set_property BOARD_PIN c2_ddr4_dq48 [get_ports {ddr4_sdram_c2_dq[48]}]
set_property BOARD_PIN c2_ddr4_dq49 [get_ports {ddr4_sdram_c2_dq[49]}]
set_property BOARD_PIN c2_ddr4_dq50 [get_ports {ddr4_sdram_c2_dq[50]}]
set_property BOARD_PIN c2_ddr4_dq51 [get_ports {ddr4_sdram_c2_dq[51]}]
set_property BOARD_PIN c2_ddr4_dq52 [get_ports {ddr4_sdram_c2_dq[52]}]
set_property BOARD_PIN c2_ddr4_dq53 [get_ports {ddr4_sdram_c2_dq[53]}]
set_property BOARD_PIN c2_ddr4_dq54 [get_ports {ddr4_sdram_c2_dq[54]}]
set_property BOARD_PIN c2_ddr4_dq55 [get_ports {ddr4_sdram_c2_dq[55]}]
set_property BOARD_PIN c2_ddr4_dq56 [get_ports {ddr4_sdram_c2_dq[56]}]
set_property BOARD_PIN c2_ddr4_dq57 [get_ports {ddr4_sdram_c2_dq[57]}]
set_property BOARD_PIN c2_ddr4_dq58 [get_ports {ddr4_sdram_c2_dq[58]}]
set_property BOARD_PIN c2_ddr4_dq59 [get_ports {ddr4_sdram_c2_dq[59]}]
set_property BOARD_PIN c2_ddr4_dq60 [get_ports {ddr4_sdram_c2_dq[60]}]
set_property BOARD_PIN c2_ddr4_dq61 [get_ports {ddr4_sdram_c2_dq[61]}]
set_property BOARD_PIN c2_ddr4_dq62 [get_ports {ddr4_sdram_c2_dq[62]}]
set_property BOARD_PIN c2_ddr4_dq63 [get_ports {ddr4_sdram_c2_dq[63]}]
set_property BOARD_PIN c2_ddr4_odt [get_ports {ddr4_sdram_c2_odt}]
set_property BOARD_PIN c2_ddr4_reset_n [get_ports {ddr4_sdram_c2_reset_n}]
set_property BOARD_PIN default_250mhz_clk2_n [get_ports {ddr4_sdram_c2_sys_clk_n}]
set_property BOARD_PIN default_250mhz_clk2_p [get_ports {ddr4_sdram_c2_sys_clk_p}]
